# Generated by Django 5.2.8 on 2025-11-29 23:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='precipitation_probability',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='wind_speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
