# Generated by Django 5.2.8 on 2025-12-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_data_post_precipitation_probability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='precipitation_probability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='wind_speed',
            field=models.FloatField(default=0),
        ),
    ]
